# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

def available_pods
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxBlocking'
    pod 'RxDataSources', '~> 0.7'
    #pod 'Action'    
end

target ‘RxDump’ do
    available_pods
end
